services:
  app:
    build: .
    #command: . docker-script/start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    command: sh -c "chmod +x docker-script/start.sh"

  db:
    image: mysql:8.0.30
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined
